version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "17:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: mix
    directory: "/"
    schedule:
      interval: "monthly"
      time: "17:00"
      timezone: "Europe/Berlin"
  - package-ecosystem: "npm"
    directory: "/assets"
    schedule:
      interval: "monthly"
      time: "17:00"
      timezone: "Europe/Berlin"
