name: Build & Push to DockerHub
on:
  push:
    branches:
      - main
env:
  MIX_ENV: test
jobs:
  build:
    name: Elixir format and tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Setup elixir
        uses: actions/setup-elixir@v1.5
        with:
          elixir-version: 1.11.4
          otp-version: 23
          experimental-otp: true
      - name: Install Dependencies
        run: mix deps.get
      - name: Setup database
        run: mix ecto.setup
      - name: Check Format
        run: mix format
      - name: Run Tests
        run: mix test
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: codegram/hey-mate:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}